config/routes.rb
Rails.application.routes.draw do
  resources :shorten_urls
  get '/:id', to: 'shorten_urls#show'
  devise_for :users

  root to: 'shorten_urls#index'
  namespace :api do
    namespace :v1 do
      defaults format: :json do
        post 'authenticate', to: 'users#authenticate'
        get 'get_all_links', to: 'shorten_urls#index'
        post 'generate_link', to: 'shorten_urls#create'
        devise_for :users, only: [:sessions]
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shorten_url.rb
class ShortenUrl < ApplicationRecord
  belongs_to :owner, polymorphic: true, optional: true

  REGEX_LINK_HAS_PROTOCOL = Regexp.new('\Ahttp:\/\/|\Ahttps:\/\/', Regexp::IGNORECASE)
  URL_REGEX = /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\Z/ix
  CHARSETS = {
    alphanum: ('a'..'z').to_a + (0..9).to_a,
    alphanumcase: ('a'..'z').to_a + ('A'..'Z').to_a + (0..9).to_a
  }
  validates :url, presence: true, format: URL_REGEX
  validates :unique_key, uniqueness: true
  around_create :generate_unique_key

  scope :unexpired, -> { where(arel_table[:expires_at].eq(nil).or(arel_table[:expires_at].gt(::Time.current))) }

  attr_accessor :custom_key, :short_url

  # ensure the url starts with it protocol and is normalized
  def self.clean_url(url)
    url = url.to_s.strip
    if url !~ REGEX_LINK_HAS_PROTOCOL && url[0] != '/'
      url = "http://#{url}"
    end
    URI.parse(url).normalize.to_s
  end

  def self.generate!(destination_url, owner, custom_key: nil, expires_at: nil, fresh: false, category: nil)
    if destination_url.is_a? ShortenUrl
      if destination_url.owner == owner && destination_url.id.present?
        destination_url
      else
        generate!(
          destination_url.url,
          owner:      owner,
          custom_key: custom_key,
          expires_at: expires_at,
          fresh:      fresh,
          category:   category
        )
      end
    else

      scope = if owner
        owner = User.find(owner[:owner][:id])
        owner.shorten_urls
      else
        self
      end
      creation_method = fresh ? 'create' : 'first_or_create'

      url_to_save = Rails.application.config.shorten_url.auto_clean_url ? clean_url(destination_url) : destination_url
      scope.where(url: url_to_save, category: category).send(
        creation_method,
        custom_key: custom_key,
        expires_at: expires_at
      )
    end
  end

  def self.generate(destination_url, owner, custom_key: nil, expires_at: nil, fresh: false, category: nil)
    begin
      generate!(
        destination_url,
        owner: owner,
        custom_key: custom_key,
        expires_at: expires_at,
        fresh: fresh,
        category: category
      )
    rescue => e
      logger.info e
      nil
    end
  end

  def self.extract_token(token_str)
    /^([#{Regexp.escape(key_chars.join)}]*).*/.match(token_str)[1]
  end

  def self.fetch_with_token(token: nil, additional_params: {}, track: true)
    shortened_url = ShortenUrl.unexpired.where(unique_key: token).first

    url = if shortened_url
      shortened_url.increment_usage_count if track
      merge_params_to_url(url: shortened_url.url, params: additional_params)
    else
      Rails.application.config.shorten_url.default_redirect || '/'
    end

    { url: url, shortened_url: shortened_url }
  end

  def self.merge_params_to_url(url: nil, params: {})
    if params.respond_to?(:permit!)
      params = params.permit!.to_h.with_indifferent_access.except!(:id, :action, :controller)
    end

    if Rails.application.config.shorten_url.subdomain
      params.try(:except!, :subdomain) if params[:subdomain] == Rails.application.config.shorten_url.subdomain
    end

    if params.present?
      uri = URI.parse(url)
      existing_params = Rack::Utils.parse_nested_query(uri.query)
      uri.query       = existing_params.with_indifferent_access.merge(params).to_query
      url = uri.to_s
    end

    url
  end

  def increment_usage_count
    self.class.increment_counter(:click_count, id)
  end

  def to_param
    unique_key
  end

  private

  def self.unique_key_candidate
    charset = key_chars
    (0...Rails.application.config.shorten_url.unique_key_length).map{ charset[rand(charset.size)] }.join
  end

  def generate_unique_key(retries = Rails.application.config.shorten_url.persist_retries)
    begin
      self.unique_key = custom_key || self.class.unique_key_candidate
      self.custom_key = nil
    end while self.class.unscoped.exists?(unique_key: unique_key)

    yield
  rescue ActiveRecord::RecordNotUnique
    if retries <= 0
      raise
    else
      retries -= 1
      retry
    end
  end

  def self.key_chars
    charset = Rails.application.config.shorten_url.charset
    charset.is_a?(Symbol) ? CHARSETS[charset] : charset
  end
end

app/controllers/api/v1/shorten_urls_controller.rb
class Api::V1::ShortenUrlsController < Api::V1::BaseController
  before_action :current_user, except: :authenticate

  def index
    results = @current_user.shorten_urls.unexpired
    per_page = 3
    links = Kaminari.paginate_array(results).page(params[:page]).per(per_page)
    links.collect! {|item|
      item[:unique_key] = shortlink(item[:unique_key])
      item
    }
    render json: {links: links, current_total: links.count, total_all: results.count, current_page: params[:page] || 1}, status: :ok
  end

  def create
    @shorten_url = ShortenUrl.new(shorten_url_params)
    @shorten_url = ShortenUrl.generate!(@shorten_url, @current_user) if @shorten_url.valid?
    if @shorten_url.present? && @shorten_url.persisted?
      render :create, status: :created
    else
      render json: @shorten_url.errors, status: :unprocessable_entity
    end
  end


  private
  def shorten_url_params
    params.permit(:url, :unique_key)
  end

  def shortlink(token)
    token = token[:unique_key] if token.is_a?(Hash)
    "#{request.base_url}/#{token}"
  end
end

app/controllers/shorten_urls_controller.rb
class ShortenUrlsController < ApplicationController
  before_action :set_shorten_url, only: %i[ edit update destroy ]

  # GET /shorten_urls or /shorten_urls.json
  def index
    results = ShortenUrl.where(owner: current_user[:id]).order('created_at DESC')
    per_page = Rails.application.config.shorten_url.per_page
    @shorten_urls = Kaminari::paginate_array(results).page(params[:page]).per(per_page)
  end

  # GET /shorten_urls/1 or /shorten_urls/1.json
  def show
    token = ShortenUrl.extract_token(params[:id])
    track = Rails.application.config.shorten_url.ignore_robots.blank? || request.human?
    url   = ShortenUrl.fetch_with_token(token: token, additional_params: params, track: track)
    redirect_to url[:url], status: :moved_permanently
  end

  # GET /shorten_urls/new
  def new
    @shorten_url = ShortenUrl.new
  end

  # GET /shorten_urls/1/edit
  def edit
  end

  # POST /shorten_urls or /shorten_urls.json
  def create
    @shorten_url = ShortenUrl.new(shorten_url_params)
    respond_to do |format|
      if @shorten_url.valid? && ShortenUrl.generate!(@shorten_url, current_user)
        format.html { redirect_to shorten_urls_url, notice: "Shorten url was successfully created." }
        format.json { render :show, status: :created, location: @shorten_url }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shorten_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shorten_urls/1 or /shorten_urls/1.json
  def update
    respond_to do |format|
      if @shorten_url.update(shorten_url_params)
        format.html { redirect_to shorten_urls_url, notice: "Shorten url was successfully updated." }
        format.json { render :show, status: :ok, location: @shorten_url }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shorten_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shorten_urls/1 or /shorten_urls/1.json
  def destroy
    @shorten_url.destroy

    respond_to do |format|
      format.html { redirect_to shorten_urls_url, notice: "Shorten url was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shorten_url
      token = ShortenUrl.extract_token(params[:id])
      @shorten_url = ShortenUrl.where(unique_key: token, owner: current_user[:id]).first
    end

    # Only allow a list of trusted parameters through.
    def shorten_url_params
      params.require(:shorten_url).permit(:owner_id, :owner_type, :url, :unique_key, :click_count, :expires_at, :created_at, :updated_at, :category)
    end
end

app/helpers/shorten_urls_helper.rb
module ShortenUrlsHelper

  def short_url(url, owner: nil, custom_key: nil, expires_at: nil, fresh: false, category: nil, url_options: {})
    short_url = ShortenUrl.generate(
      url,
      owner:      owner,
      custom_key: custom_key,
      expires_at: expires_at,
      fresh:      fresh,
      category:   category
    )

    if short_url
      if subdomain == Rails.application.config.shorten_url.subdomain
        url_options = url_options.merge(subdomain: subdomain)
      end

      options = { controller: :"/shorten_urls", action: :show, id: short_url.unique_key, only_path: false }.merge(url_options)
      url_for(options)
    else
      url
    end
  end

  def short_link(token)
    token = token[:unique_key] if token.is_a?(Hash) || token.is_a?(Array) || token.is_a?(Object)
    "#{request.base_url}/#{token}"
  end
end

app/views/shorten_urls/_form.html.erb
<%= form_with(model: shorten_url, local: true) do |form| %>
  <% if shorten_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shorten_url.errors.count, "error") %> prohibited this shorten_url from being saved:</h2>

      <ul>
      <% shorten_url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :owner_id, {value: current_user.id} %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_area :url , cols: 100 %>
  </div>

  <div class="field">
    <%= form.label :unique_key, 'Unique key' %>
    <%= form.text_field :unique_key %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shorten_urls/edit.html.erb
<h1>Editing Shorten Url</h1>

<%= render 'form', shorten_url: @shorten_url %>

<%= link_to 'Show', @shorten_url %> |
<%= link_to 'Back', shorten_urls_path %>

app/views/shorten_urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shorten Urls</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Short URL</th>
      <th>Click count</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shorten_urls.each do |shorten_url| %>
      <tr>
        <td><%= shorten_url.url %></td>
        <td><%= link_to(nil, short_link(shorten_url)) %></td>
        <td align="center"><%= shorten_url.click_count %></td>
        <td><%= shorten_url.created_at %></td>
        <td><%= link_to 'Show', short_link(shorten_url) %></td>
        <td><%= link_to 'Edit', edit_shorten_url_path(shorten_url) %></td>
        <td><%= link_to 'Destroy', shorten_url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate(@shorten_urls) %>
<br>

<%= link_to 'New Shorten Url', new_shorten_url_path %>

app/views/shorten_urls/new.html.erb
<h1>New Shorten Url</h1>

<%= render 'form', shorten_url: @shorten_url %>

<%= link_to 'Back', shorten_urls_path %>

app/views/shorten_urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @shorten_url.owner %>
</p>

<p>
  <strong>Url:</strong>
  <%= @shorten_url.url %>
</p>

<p>
  <strong>Unique key:</strong>
  <%= @shorten_url.unique_key %>
</p>

<p>
  <strong>Click count:</strong>
  <%= @shorten_url.click_count %>
</p>

<p>
  <strong>Expires at:</strong>
  <%= @shorten_url.expires_at %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @shorten_url.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @shorten_url.updated_at %>
</p>

<p>
  <strong>Category:</strong>
  <%= @shorten_url.category %>
</p>

<%= link_to 'Edit', edit_shorten_url_path(@shorten_url) %> |
<%= link_to 'Back', shorten_urls_path %>